version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://server:8080/healthcheck/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      server:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5