version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://server:${SERVER_PORT}/healthcheck/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      server:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5